name: training_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  #State managment 
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  #Navigation
  go_router: ^17.2.3

  #Backend 
  supabase_flutter: ^2.12.4

  #Env_variable
  flutter_dotenv: ^6.0.1

  #Local storage (settings)
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env